### PR TITLE
fix: show simple editor on mobile

### LINKED ISSUE #380: Select/Copy/Paste doesn't work on iOS when editing config files
Latest Fluidd build won't let me select/copy/paste bits of config when using the build-in editor.

This worked in earlier builds, before the more fancy VCCode style editor was added.

### PR DESCRIPTION
**Pull request by pedrolamas**
Monaco Editor is not supported on mobile devices (it says so on [their page](https://microsoft.github.io/monaco-editor/)), so instead of having a broken editing experience in mobile devices, better to just use a simple text area!

This change can be easily tested by changing the browser User Agent to a mobile one.

Screenshot from my own OnePlus Android phone:

image

Fixes #380

Signed-off-by: Pedro Lamas <pedrolamas@gmail.com>

### CODE REVIEW

File: src/components/widgets/filesystem/FileEditorTextOnly.vue [hunk 1]
```diff
@@ -0,0 +1,42 @@
+<template>
+  <textarea
+    class="editor v-input v-textarea theme--dark"
+    :readonly="readonly"
+    :value="value"
```
Comment (matmen) [inline src/components/widgets/filesystem/FileEditorTextOnly.vue:5]:
```suggestion
    :value="value"
    :spellcheck="false"
```

File: src/components/widgets/filesystem/FileEditorTextOnly.vue [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+}
+</script>
+
+<style lang="scss" scoped>
+  .editor {
+    font-family: monospace;
+    font-size: 1rem;
+    font-weight: 100 !important;
+    min-width: 100%;
+    height: 90% !important;
```
Comment (matmen) [inline src/components/widgets/filesystem/FileEditorTextOnly.vue:38]:
```suggestion
```

File: src/util/is-mobile.ts [hunk 3]
```diff
@@ -0,0 +1,5 @@
+const isMobile = () => {
+  return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)
```
Comment (matmen) [inline src/util/is-mobile.ts:2]:
```suggestion
  return (navigator as any).userAgentData?.mobile ?? /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)
```
for browsers that support it (probably more reliable), fallback to your way

File: src/components/widgets/filesystem/FileEditorTextOnly.vue (hunk 2 above)
Comment (matmen) [reply src/components/widgets/filesystem/FileEditorTextOnly.vue:38]: overwritten by next line

**Review by matmen — CHANGES_REQUESTED** [review]

File: src/components/widgets/filesystem/FileEditorTextOnly.vue [hunk 4]
```diff
@@ -0,0 +1,42 @@
+<template>
+  <textarea
+    class="editor v-input v-textarea theme--dark"
```
Comment (matmen) [inline src/components/widgets/filesystem/FileEditorTextOnly.vue:3]: looks like i forgot to add this comment: i think line starts are kinda hard to read on mobile, so a padding would be good here (just like monaco has)
```suggestion
    class="editor v-input v-textarea theme--dark px-2"
```

other than that it lgtm :)

**Review by matmen — CHANGES_REQUESTED** [review]

**Review by matmen — APPROVED** [review]
